### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的程序

### ISSUE THREAD

**Issue by DidaDidaDidaD** [ckkelvinchan/RealBasicVSR#50]
I report an error when I run the following command：ImportError: DLL load failed: 找不到指定的程序，show to solve it ,thank you

**Comment by DidaDidaDidaD** [comment]
win10 system, 64bit

**Comment by DidaDidaDidaD** [comment]
![image](https://user-images.githubusercontent.com/83280021/169006473-dea33195-3381-4a84-8359-07e472bfa2b1.png)

**Comment by DidaDidaDidaD** [comment]
以上错误在python3.7，换成python3.8报错变了点
(real-basicvsr) F:\sourcecode\RealBasicVSR-master>python inference_realbasicvsr.py configs/realbasicvsr_x4.py checkpoints/RealBasicVSR_x4.pth data/demo_001 results/demo_001
Traceback (most recent call last):
  File "inference_realbasicvsr.py", line 12, in <module>
    from realbasicvsr.models.builder import build_model
  File "F:\sourcecode\RealBasicVSR-master\realbasicvsr\models\builder.py", line 3, in <module>
    from mmedit.models.registry import BACKBONES, COMPONENTS, LOSSES, MODELS
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmedit\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401, F403
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmedit\models\backbones\__init__.py", line 14, in <module>
    from .sr_backbones import (EDSR, LIIFEDSR, LIIFRDN, RDN, SRCNN, BasicVSRNet,
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmedit\models\backbones\sr_backbones\__init__.py", line 3, in <module>
    from .basicvsr_pp import BasicVSRPlusPlus
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmedit\models\backbones\sr_backbones\basicvsr_pp.py", line 6, in <module>
    from mmcv.ops import ModulatedDeformConv2d, modulated_deform_conv2d
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "E:\software-install-dir\Anaconda3\envs\real-basicvsr\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

**Comment by ckkelvinchan** [comment]
This should be a problem for windows. From here
```
ext = importlib.import_module('mmcv.' + name)
```
It should be related to the installation of `mmcv`.

**Comment by DidaDidaDidaD** [comment]
> This should be a problem for windows. From here
> 
> ```
> ext = importlib.import_module('mmcv.' + name)
> ```
> 
> It should be related to the installation of `mmcv`.

Thank you,I have solved it

**Comment by ckkelvinchan** [comment]
Great!

**Comment by Noah-cj** [comment]
should i install mmcv?

**Comment by learner-dhx** [comment]
> ?

how do you resove it , could you please tell me ?
