### ISSUE TITLE
KeyError: 'UNetDiscriminatorWithSpectralNorm is already registered in component'

### ISSUE THREAD

**Issue by sunyuxiu** [ckkelvinchan/RealBasicVSR#6]
Hi,when I run the program of "Video as input and output" and meet the problem in title.What is the solution to this problem?

**Comment by sunyuxiu** [comment]
> Hi,when I run the program of "Video as input and output" and meet the problem in title.What is the solution to this problem?

After I downloaded the pre-train-weight and test the video.

**Comment by ckkelvinchan** [comment]
Did you follow the installation instructions, and did you modify the code? I just tried and there is no problem on my side.

**Comment by sunyuxiu** [comment]
>>> from realbasicvsr.models.builder import build_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/__init__.py", line 2, in <module>
    from .components import UNetDiscriminatorWithSpectralNorm
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/components/__init__.py", line 1, in <module>
    from .unet_disc import UNetDiscriminatorWithSpectralNorm
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/components/unet_disc.py", line 9, in <module>
    class UNetDiscriminatorWithSpectralNorm(nn.Module):
  File "/home/ubuntu/anaconda3/envs/test/lib/python3.6/site-packages/mmcv/utils/registry.py", line 312, in _register
    module_class=cls, module_name=name, force=force)
  File "/home/ubuntu/anaconda3/envs/test/lib/python3.6/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'UNetDiscriminatorWithSpectralNorm is already registered in component'
I install the package and the envrionment as in the installations,including the pytorch,openmim,mmcv-full and mmedit.It is Ok to run in python.I didn't modify the code,either.
Sorry,I still can not find where is error.Here is the keyerror message.Is there the mmcv has some problem?

**Comment by ckkelvinchan** [comment]
What do you mean by "It is ok to run in Python"? 

You can also take a look at the Colab demo. It can be run normally.

**Comment by sunyuxiu** [comment]
I install successful the mim,mmcv-full and mmedit.

**Comment by ckkelvinchan** [comment]
I am sorry that I still could not reproduce your error. Could you try directly on Python in terminal and type `from realbasicvsr.models.builder import build_model`?

**Comment by sunyuxiu** [comment]
When I run on python terminal and type `from realbasicvsr.models.builder import build_model`，I got the following information:
>>> from realbasicvsr.models.builder import build_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/__init__.py", line 2, in <module>
    from .components import UNetDiscriminatorWithSpectralNorm
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/components/__init__.py", line 1, in <module>
    from .unet_disc import UNetDiscriminatorWithSpectralNorm
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/components/unet_disc.py", line 9, in <module>
    class UNetDiscriminatorWithSpectralNorm(nn.Module):
  File "/home/ubuntu/anaconda3/envs/test/lib/python3.6/site-packages/mmcv/utils/registry.py", line 312, in _register
    module_class=cls, module_name=name, force=force)
  File "/home/ubuntu/anaconda3/envs/test/lib/python3.6/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'UNetDiscriminatorWithSpectralNorm is already registered in component'

**Comment by sunyuxiu** [comment]
When I run on python terminal and type from `realbasicvsr.models.builder import build_model`，I got the following information:
`>>> from realbasicvsr.models.builder import build_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/__init__.py", line 2, in <module>
    from .components import UNetDiscriminatorWithSpectralNorm
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/components/__init__.py", line 1, in <module>
    from .unet_disc import UNetDiscriminatorWithSpectralNorm
  File "/home/ubuntu/RealBasicVSR-master/realbasicvsr/models/components/unet_disc.py", line 9, in <module>
    class UNetDiscriminatorWithSpectralNorm(nn.Module):
  File "/home/ubuntu/anaconda3/envs/test/lib/python3.6/site-packages/mmcv/utils/registry.py", line 312, in _register
    module_class=cls, module_name=name, force=force)
  File "/home/ubuntu/anaconda3/envs/test/lib/python3.6/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'UNetDiscriminatorWithSpectralNorm is already registered in component'
`

**Comment by batectin** [comment]
This probably because of your pip environment. The _mmedit_ package will clash with the _mmediting_ to be specific (if you run both of them under the same env). Simply just remove and reinstall mmedit will solve. Note that do it outside of the _mmediting_ folder

**Comment by sunyuxiu** [comment]
> This probably because of your pip environment. The _mmedit_ package will clash with the _mmediting_ to be specific (if you run both of them under the same env). Simply just remove and reinstall mmedit will solve. Note that do it outside of the _mmediting_ folder

As you said, I uninstalled mmedit first, and then reinstalled mmedit. When I ran it again, it worked.Thanks!
