### ISSUE TITLE
Install problem 

### ISSUE THREAD

**Issue by Regradert** [ckkelvinchan/RealBasicVSR#67]
Hello. First of all congratulations on your application. I would like to try it but I get an error that I do not know how to solve:

```
(base) PS C:\RealBasicVSR-master> python inference_realbasicvsr.py configs/realbasicvsr_x4.py checkpoints/RealBasicVSR_x4.pth data/demo_000 results/demo_000
Traceback (most recent call last):
  File "C:\RealBasicVSR-master\inference_realbasicvsr.py", line 10, in <module>
    from mmedit.core import tensor2img
  File "C:\Users\pipo\anaconda3\lib\site-packages\mmedit\__init__.py", line 30, in <module>
    assert (mmcv_min_version <= mmcv_version <= mmcv_max_version), \
AssertionError: mmcv==1.6.1 is used but incompatible. Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).
```

I'm new to handling the terminal and maybe I'm doing something wrong. I install **mim install mmcv-full** but it supposedly tells me the version is incompatible. Can someone give me a hand? Thanks.

**Comment by summerwang0806** [comment]
报错提示：Please install mmcv-full>=(1, 3, 13, 0, 0, 0), <=(1, 6, 0, 0, 0, 0).
其实就是mmcv版本太高了，按照指定版本安装就行，(不要用mmcv-full
`mim uninstall mmcv`
`mim install mmcv==1.3.13`

**Comment by LVFENGCHUN** [comment]
AssertionError: mmcv==1.7.2 is used but incompatible. Please install mmcv-full>=(2, 0, 0, 0, -1, 1), <(2, 1, 0, 0, 0, 0).
